### ISSUE TITLE
Deprecate claimant

### ISSUE THREAD

**Issue by larsrh** [typelevel/claimant#110]
[expecty](https://github.com/eed3si9n/expecty) is similar to Claimant and has Dotty support. It is not developed further, except for as part of [nanotest](https://github.com/scala/nanotest-strawman/). We could scrap the entire code and replace it with expecty.

**Comment by larsrh** [comment]
Inside of Typelevel, Claimant is only used in Jawn. Maybe we should deprecate it altogether.

**Comment by SethTisue** [comment]
fyi @eed3si9n

**Comment by eed3si9n** [comment]
Disney Streaming folks also use Expecty for Weaver Test - https://github.com/disneystreaming/weaver-test

**Comment by larsrh** [comment]
I created #138 and unless anyone objects in the next few days I'll merge and archive the repository.

**Comment by SethTisue** [comment]
fyi @Baccata @keynmol

**Comment by Baccata** [comment]
Acked

**Comment by SethTisue** [comment]
and archive the repo?

**Comment by larsrh** [comment]
Maybe someone finds a bug in which case I'm inclined to merge a fixing PR :wink:
