### ISSUE TITLE
Cats dependency

### ISSUE THREAD

**Issue by larsrh** [typelevel/claimant#14]
There is a dependency on Cats in claimant's tests, which severely reduces the velocity of releases for new Scala versions.

Is that test essential? Could we remove it?

**Comment by travisbrown** [comment]
+1. I proposed this [here](https://github.com/typelevel/jawn/issues/160#issuecomment-486152563) but then we got the Cats release out so I didn't worry about it, but I think it makes sense.

**Comment by larsrh** [comment]
OK, PR upcoming.
