### ISSUE TITLE
publish for Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by SethTisue** [typelevel/claimant#4]
RC1 is on Maven Central

**Comment by SethTisue** [comment]
blocked for now by https://github.com/typelevel/cats/issues/2776

**Comment by travisbrown** [comment]
We've got a Cats milestone for 2.13.0-RC1, so I just opened #8, #9, and #10.

**Comment by non** [comment]
We've merged all the PRs so I'll try to do a release later tonight and will report back here when it's done.

**Comment by travisbrown** [comment]
Thanks @non!

**Comment by non** [comment]
Spent some time on this last night but it turns out my work laptop doesn't have the needed configuration/credentials. I'll be back home tonight and will comment here once the release is out.

**Comment by travisbrown** [comment]
@non I'd be happy to publish it now that it's going to `org.typelevel` if that'd be more convenient.

**Comment by non** [comment]
@travisbrown yes please! thanks!

**Comment by travisbrown** [comment]
@non Great, thanks! What do you think of creating `https://github.com/typelevel/claimant/` to match?

**Comment by non** [comment]
@travisbrown Sounds good. I'll move it now.

**Comment by travisbrown** [comment]
@non Thanks! I'm running the release now from the current master here, will push the tag etc. when the new repo is ready.

**Comment by non** [comment]
@travisbrown OK if I add you as a maintainer while I'm at it?

**Comment by non** [comment]
Project now lives at https://github.com/typelevel/claimant.

**Comment by travisbrown** [comment]
Sure, of course. Maybe wait to update master until the release commit is in, though?

**Comment by non** [comment]
Sure thing. 👍

**Comment by non** [comment]
Alright, added @travisbrown as a maintainer. I'm about to go to the airport so I'll be offline for awhile, but please feel free to push any README updates with maintainer information.

**Comment by non** [comment]
0.1.0 is out which closes this issue.
