### ISSUE TITLE
Use Typelevel package

### ISSUE THREAD

**Issue by travisbrown** [typelevel/claimant#6]
Following up on #5, could claimant move its packaging under `org.typelevel`? I'm considering dropping ScalaTest in circe and would like to use claimant, and I'd prefer to have dependencies with idiomatic packaging—I hate writing `_root_.claimant` or whatever just because I have some kind of compatibility module of my own.

**Comment by non** [comment]
Sure! 👍

**Comment by non** [comment]
Once I've released I'll update the examples in the README.

**Comment by non** [comment]
The 0.1.0 release happened and the README is up to date so I think this issue is closed. Thanks!
